### PR TITLE
T.Writable is not exported #11

### LINKED ISSUE #11: T.Writable is not exported
#### Describe the bug
T.Writable is not exported.
Currently can only be accessed by 
```ts
import {Writable} from 'ts-toolbelt/out/types/src/Tuple/Writable';
```

#### Possible Solution
Add to `Tuple/_api.d.ts`
```ts
export { Writable } from './Writable';
```

### PR DESCRIPTION
**Pull request by regevbr**
## 🎁 Pull Request

* [x] Used a clear / meaningful title for this pull request
* [x] Tested the changes in your own code (on your projects)
* [x] Added / Edited tests to reflect changes (`tst` folder)
* [x] Have read the **Contributing** part of the **Readme**
* [x] Passed `npm test`

#### Fixes
Fix T.Writable is not exported #11 

#### Why have you made changes?
To fix #11

#### What changes have you made?
* Added missing exports to the `Tuple/_api.d.ts` file.
* Added tests to T.Writable
* Added support for T.Writable to accept readonly arrays

#### What tests have you updated?
* tested this in `tst/Tuple.ts`

#### Is there any breaking changes?
* [ ] Yes, I changed the public API & documented it
* [ ] Yes, I changed existing tests
* [x] No,  I added to the public API & documented it
* [ ] No,  I added to the existing tests
* [ ] I don't know

### CODE REVIEW

**Comment by regevbr** [comment]
@pirix-gh I hope this PR will suite your standards

**Comment by pirix-gh** [comment]
I'm investigating your PR to see if this could be applied to all the types

**Comment by pirix-gh** [comment]
TypeDoc is giving me problems generating the docs when using `readonly`... They don't support it

**Comment by pirix-gh** [comment]
Seems like I'll have to add `ReadonlyArray` to bypass that. For now, till I write a proper doc generator.

**Comment by regevbr** [comment]
So what do you want to do about it?

**Comment by pirix-gh** [comment]
Ok, it's not possible to generalize it like I said. But it's now fixed with your changes. Thanks!

(v2.1.5)

**Comment by regevbr** [comment]
Always happy to help!

**Comment by regevbr** [comment]
Feel free to assign me future issues

**Comment by pirix-gh** [comment]
There's going to be a 3.x update with a few breaking changes. Those will improve type soundness and provide computations that have minimum impact on the global performance. It's a sacrifice that is needed.
The changes concern the `Boolean` mostly (API change), but will also impact (Internally) a few other types.

**Comment by regevbr** [comment]
When can we expect that version? I will defer my work until then as I use this library extensively now

**Comment by pirix-gh** [comment]
I don't know for sure. But I'm giving myself a deadline of 5-6 days from now, going to try to rush it though. I'll keep you updated.

**Pull request merged**
