### PR TITLE
add F.LengthOf

### PR DESCRIPTION
**Pull request by artalar**
## 🎁 Pull Request

* [x] Used a clear / meaningful title for this pull request
* [ ] Tested the changes in your own code (on your projects)
* [x] Added / Edited tests to reflect changes (`tst` folder)
* [x] Have read the **Contributing** part of the **Readme**
* [x] Passed `npm test`

#### Why have you made changes?

I was spent an hour for resolve function length with type inference and, finally, find the solution. I propose to add it to ts-toolbelt

#### What changes have you made?
* add `F.LengthOf`

#### What tests have you updated?
* tested this in `tst/Function.ts`

#### Is there any breaking changes?

* [ ] Yes, I changed the public API & documented it
* [ ] Yes, I changed existing tests
* [x] No,  I added to the public API & documented it
* [ ] No,  I added to the existing tests
* [ ] I don't know

### CODE REVIEW

**Comment by artalar** [comment]
`Tested the changes in your own code (on your projects)` is not checked because I needed it in side test project

**Comment by artalar** [comment]
`Tested the changes in your own code (on your projects)` is not checked because I wrote it when experimenting with some task, but finally, choose a different workaround

**Comment by pirix-gh** [comment]
Hi @artalar, thanks for your pull request.

I will merge it with the v3 as soon as it's ready for its release (`next` branch)
FYI, at this moment, I am completing docs, examples and some extra tests.

Thanks!

**Comment by ctrlplusb** [comment]
Writing docs for an open source lib is so much effort! 😀 Been taking me ages with mine and still not done.

**Comment by pirix-gh** [comment]
I found your docs quite complete though (the ones for easy-peasy)! That is a decent website, I believe that it is a lot of work. Hopefully, you will be able to get paid for it, as jobs get more decentralized in the future :moneybag:

**Comment by pirix-gh** [comment]
@artalar It's out! I just renamed the type to `Length` to keep it consistent with the v3 names.

Thanks for your contribution!

**Pull request merged**
