### PR TITLE
Object.PathOf to get the path of a given object.

### PR DESCRIPTION
**Pull request by kimamula**
## 🎁 Pull Request

* [x] Used a clear / meaningful title for this pull request
* [x] Tested the changes in your own code (on your projects)
* [x] Added / Edited tests to reflect changes (`tst` folder)
* [x] Have read the **Contributing** part of the **Readme**
* [x] Passed `npm test`

#### Why have you made changes?

While several types related to Object path have already been provided, there is no type to get the path of a given object.

#### What changes have you made?
* Declare `Object.PathOf`

#### What tests have you updated?
* Add a test for `Object.PathOf`

#### Is there any breaking changes?

* [ ] Yes, I changed the public API & documented it
* [ ] Yes, I changed existing tests
* [x] No,  I added to the public API & documented it
* [ ] No,  I added to the existing tests
* [ ] I don't know

### CODE REVIEW

**Comment by pirix-gh** [comment]
Hi @kimamula I merged your request, but in the end I kept nothing of it.

Why? The type you proposed did not work for n-depth objects, but only for your example.
But I kept your nice idea and so I created a type called `Paths` that does the same thing.

There's is one difference though, the types are also more compact. And if you need to validate a path, you can use `PathValid`, that will help you handle errors more gracefully. https://github.com/pirix-gh/ts-toolbelt/issues/4#issuecomment-506217908

Let me know if you're satisfied, if not please open an issue :)

**Comment by kimamula** [comment]
> The type you proposed did not work for n-depth objects, but only for your example.

Well, it was likely working as the below test passes, though I may be missing something.

```ts
type PATHSOF_O = {
    a: {
        a: {}
    }
    b: {
        a: {}
        b: {
          c: {
            d: {
              e: {}
            }
          }
        }
    }
}

checks([
    check<O.PathOf<PATHSOF_O>, ['a'] | ['b'] | ['a', 'a'] | ['b', 'a'] | ['b', 'b'] | ['b', 'b', 'c'] | ['b', 'b', 'c', 'd'] | ['b', 'b', 'c', 'd', 'e'], Test.Pass>(),
])
```

Anyway, `Paths` fills my requirement so it's OK.
Thanks for your great work on this fantastic library!

**Comment by pirix-gh** [comment]
@kimamula I am very sorry! Yes it was working, indeed. My mistake. Apologies.

However, thanks for the idea. I re-wrote your type to make it more lightweight, though. You can go look, I do multiple `Prepend` instead of `Concat`. At the end of the computations, we are then left with a reversed path (because of using `Prepend`) that I `Reverse` only once.

You must be careful with `Concat` because it will loop and `Reverse` twice for each loop you do, which can make TS inefficient (imagine that many projects start using this type).

And as a matter of fact, there's is no real difference (in practice) between `['a'] | ['a', 'b']` and `['a'?, 'b'?]`.
(Note that I had to remove `undefined` for all the items of the latter to do so).

Happy coding

**Comment by kimamula** [comment]
Ah, I see what you mean. Yes, `PathValid` also fits my use case. I could not have imagined that this type can be used in that way. Very interesting.

And thanks for the detailed explanation of the performance difference between multiple `Prepend` and `Concat`.
That totally makes sense :)

**Comment by pirix-gh** [comment]
I am busy writing examples, so in the future you will see how to do this :)

**Pull request merged**
